development:
  session_key: kzak_development
  session_secret: 500cad18bf781eae3800b34aad609361
  secret_token: c0377edbd88984c5e393b173b43fb8c7fdec4b
  app_name: example
  domain: http://kzak.local
  mailer: noreply@example.com

test:
  session_key: kzak_test
  session_secret: 0b5e5ab4ac1797c32911814431a5b2fb
  secret_token: c0377edbd88984c5e393b173b43fb8c7fdec4bf7a6

production:
  session_key: # any unique string that identifies your app
  session_secret: # run "rake secret" to generate a session secret
  secret_token: # run "rake secret" to generate a secret token
  app_name: # the name of your application, e.g. "KZAK"
  domain: # http://example.com # the url for your application
  mailer: # noreply@example.com # the from address for outgoing emails
  s3_access_id: # sign up for Amazon S3 at http://aws.amazon.com/s3/
  s3_secret_key: # ...then go to Your Account->Security Credentials to get your access_id and secret_key
  s3_bucket_name: # ...then choose a name for your bucket, set it here, and run "rake s3:create"
  s3_host_alias: # (optional) provide your cloudfront CNAME http://aws.amazon.com/cloudfront
  HOPTOAD_API_KEY: # Sign up at http://hoptoadapp.com and provide your API key for exception notification emails
  smtp_address: # smtp.gmail.com
  smtp_port: # 587
  smtp_user_name: # example@gmail.com
  smtp_password: # password
  smtp_authentication: # plain
  smtp_enable_starttls_auto: # true
  smtp_domain: # example.com # omit if using a normal Gmail account
